-- Auto-generated by scripts/import-howtocook.ts
-- source: HowToCook public base recipes (family_id IS NULL)
-- generated_at: 2026-07-17T07:39:02.772Z count: 5

INSERT OR IGNORE INTO recipes (
  id, family_id, parent_recipe_id,
  name, normalized_name, category, tags, source, summary, cover_image_url, steps_json
) VALUES (
  'base_htc_meat_dish_2aa39281',
  NULL,
  NULL,
  '冬瓜酿肉',
  '冬瓜酿肉',
  '荤菜',
  '["家常","清淡","蒸煮"]',
  'howtocook',
  '冬瓜酿肉是一道荤素搭配的家常蒸菜，口感鲜嫩爽滑，清爽不腻。',
  'https://raw.githubusercontent.com/Anduin2017/HowToCook/master/dishes/meat_dish/冬瓜酿肉/冬瓜酿肉成品.jpg',
  '["冬瓜去皮，切成25cm长3cm厚的片。","将切好的冬瓜放入碗中，放入15g盐抹匀，放置10分钟。","换个碗放入肉末、葱姜末、5g盐、淀粉5g、胡椒粉、生抽。","用筷子顺时针搅拌至食材颜色均匀（约2分钟）。","将腌制好的冬瓜用清水洗三遍。","拿一片冬瓜片卷起来，塞入肉馅。","放入碟子中，摆到碟子边缘。","打入一个鸡蛋到中间圆圈处。","放入蒸锅，水开后蒸15分钟，盖上锅盖。","开盖取出蒸好的冬瓜酿肉。","将蒸出的水倒入锅中，加入水淀粉和50ml清水烧开。","淋到冬瓜酿肉上。"]'
);
INSERT OR IGNORE INTO recipe_ingredients (
  id, recipe_id, name, normalized_name, amount
) VALUES (
  'base_htc_meat_dish_2aa39281_ing_1',
  'base_htc_meat_dish_2aa39281',
  '猪肉末',
  '猪肉末',
  '150g'
);
INSERT OR IGNORE INTO recipe_ingredients (
  id, recipe_id, name, normalized_name, amount
) VALUES (
  'base_htc_meat_dish_2aa39281_ing_2',
  'base_htc_meat_dish_2aa39281',
  '冬瓜',
  '冬瓜',
  '100g'
);

INSERT OR IGNORE INTO recipes (
  id, family_id, parent_recipe_id,
  name, normalized_name, category, tags, source, summary, cover_image_url, steps_json
) VALUES (
  'base_htc_meat_dish_c9e7aaac',
  NULL,
  NULL,
  '冷吃兔',
  '冷吃兔',
  '荤菜',
  '["辣口","下饭","煎炒"]',
  'howtocook',
  '经典四川自贡菜，麻辣干香，兔肉紧实有嚼劲，高蛋白低脂肪。需多种香料和火候，放一夜更入味。',
  NULL,
  '["蒜、姜剁碎备用，八角、桂皮、香叶、山奈、白蔻、小茴香洗净备用。","干辣椒剪成2厘米小段，洗净备用。","小葱/大葱/洋葱洗净，洋葱切块。","兔肉剁成2厘米小块，加盐、料酒、味精腌制15分钟。","锅中倒油（油量需淹没兔肉），油温4成热下小葱/大葱/洋葱，中小火煸炒出香味，待微焦后捞出。","开大火升高油温至8成热，下入兔肉，转中小火炸至微微焦黄后捞出。","升高油温，倒入干辣椒、青花椒、八角、桂皮、香叶、山奈、白蔻、小茴香，转小火将辣椒段炸脆（注意不要炸糊）。","重新倒入兔肉，加入蚝油翻炒几分钟。","关火，加入蒜、姜、白芝麻，翻炒均匀。","放置一夜更加入味。"]'
);
INSERT OR IGNORE INTO recipe_ingredients (
  id, recipe_id, name, normalized_name, amount
) VALUES (
  'base_htc_meat_dish_c9e7aaac_ing_1',
  'base_htc_meat_dish_c9e7aaac',
  '兔肉',
  '兔肉',
  '200g'
);

INSERT OR IGNORE INTO recipes (
  id, family_id, parent_recipe_id,
  name, normalized_name, category, tags, source, summary, cover_image_url, steps_json
) VALUES (
  'base_htc_meat_dish_7807ba14',
  NULL,
  NULL,
  '凉拌鸡丝',
  '凉拌鸡丝',
  '荤菜',
  '["少油","家常","凉菜"]',
  'howtocook',
  '无油低卡的家常凉菜，鸡丝嫩滑入味，麻油与香醋调和出微麻微酸的清爽口感，适合夏日解腻。',
  'https://raw.githubusercontent.com/Anduin2017/HowToCook/master/dishes/meat_dish/凉拌鸡丝/凉拌鸡丝.jpg',
  '["姜切片，备用。","锅中倒入4升水。","加入鸡胸肉、姜片。","倒入20毫升料酒。","开大火不盖盖将水烧开。","水开后转中火，用勺子将浮沫捞出。","继续煮5-7分钟（非冷冻5分钟，冷冻7分钟）。","用筷子插入鸡胸肉，如果能轻松插入，代表熟了；否则延长煮制时间。","用凉白开水冲泡鸡胸肉，使降至室温。","顺着鸡胸肉纹理撕成细丝。","准备一个碗。","碗中加入麻油、生抽、香醋、白糖、盐。","搅拌料汁，使糖和盐尽量溶化。","将料汁倒入鸡丝中，搅拌均匀。"]'
);
INSERT OR IGNORE INTO recipe_ingredients (
  id, recipe_id, name, normalized_name, amount
) VALUES (
  'base_htc_meat_dish_7807ba14_ing_1',
  'base_htc_meat_dish_7807ba14',
  '鸡胸肉',
  '鸡胸肉',
  '200克'
);

INSERT OR IGNORE INTO recipes (
  id, family_id, parent_recipe_id,
  name, normalized_name, category, tags, source, summary, cover_image_url, steps_json
) VALUES (
  'base_htc_meat_dish_519a666f',
  NULL,
  NULL,
  '农家一碗香',
  '农家一碗香',
  '荤菜',
  '["下饭","辣口","快手"]',
  'howtocook',
  '咸香下饭的湖南家常小炒，五花肉油润，鸡蛋嫩滑，青椒清香，口感层次丰富。',
  'https://raw.githubusercontent.com/Anduin2017/HowToCook/master/dishes/meat_dish/农家一碗香/农家一碗香成品.jpg',
  '["将猪肉切片，肥瘦分开放；青椒和小米辣切段；蒜拍成末，姜切丝；鸡蛋打散备用。","锅中倒油，小火加热，倒入蛋液炒散至断生，盛出备用。","锅中补油，小火，放入肥猪肉煸出猪油。","肥肉金黄时转中火，放入瘦肉翻炒至变色。","加入姜丝、蒜末和豆瓣酱翻炒均匀上色。","放入青红椒、鸡蛋，加酱油和白糖，翻炒至青椒微微断生。","出锅装盘。"]'
);
INSERT OR IGNORE INTO recipe_ingredients (
  id, recipe_id, name, normalized_name, amount
) VALUES (
  'base_htc_meat_dish_519a666f_ing_1',
  'base_htc_meat_dish_519a666f',
  '猪肉（五花肉）',
  '猪肉（五花肉）',
  '250g'
);
INSERT OR IGNORE INTO recipe_ingredients (
  id, recipe_id, name, normalized_name, amount
) VALUES (
  'base_htc_meat_dish_519a666f_ing_2',
  'base_htc_meat_dish_519a666f',
  '青椒',
  '青椒',
  '3个'
);

INSERT OR IGNORE INTO recipes (
  id, family_id, parent_recipe_id,
  name, normalized_name, category, tags, source, summary, cover_image_url, steps_json
) VALUES (
  'base_htc_meat_dish_fb1dfdfc',
  NULL,
  NULL,
  '乡村啤酒鸭',
  '乡村啤酒鸭',
  '荤菜',
  '["下饭","家常","辣口"]',
  'howtocook',
  '鸭肉与啤酒同炖，汤汁浓郁，肉质鲜香软烂，带淡淡的啤酒清香，是一道风味独特的家常菜。步骤稍多但操作简单。',
  NULL,
  '["鸭肉清洗放入锅中，加清水淹没，加20ml料酒、1根大葱、2厘米生姜，烧滚后捞出浮沫，将鸭肉捞出清水洗净。","锅烧热加60ml花生油，油温60度时加入鸭肉翻炒4分钟。","2分钟后加入所有香料（草果、桂皮、八角、香叶、干辣椒），3分钟时加入所有料头（生姜、大蒜、小米辣）。","加入1000ml啤酒，烧鸭肉30分钟。","10分钟时加盐3克、生抽10ml、老抽5ml；20分钟时加入青红椒段；29分钟时加入蒜苗段和大葱段，翻炒1分钟。","出锅。"]'
);
INSERT OR IGNORE INTO recipe_ingredients (
  id, recipe_id, name, normalized_name, amount
) VALUES (
  'base_htc_meat_dish_fb1dfdfc_ing_1',
  'base_htc_meat_dish_fb1dfdfc',
  '鸭肉',
  '鸭肉',
  '200g'
);
INSERT OR IGNORE INTO recipe_ingredients (
  id, recipe_id, name, normalized_name, amount
) VALUES (
  'base_htc_meat_dish_fb1dfdfc_ing_2',
  'base_htc_meat_dish_fb1dfdfc',
  '啤酒',
  '啤酒',
  '250ml'
);
INSERT OR IGNORE INTO recipe_ingredients (
  id, recipe_id, name, normalized_name, amount
) VALUES (
  'base_htc_meat_dish_fb1dfdfc_ing_3',
  'base_htc_meat_dish_fb1dfdfc',
  '青椒',
  '青椒',
  '1条'
);
INSERT OR IGNORE INTO recipe_ingredients (
  id, recipe_id, name, normalized_name, amount
) VALUES (
  'base_htc_meat_dish_fb1dfdfc_ing_4',
  'base_htc_meat_dish_fb1dfdfc',
  '红椒',
  '红椒',
  '1条'
);

