import type { Recipe } from "./types";

export const recipeCategories = ["全部", "家常菜", "荤菜", "素菜", "汤羹", "主食"];
export const recommendationTags = ["全部", "荤菜", "素菜", "汤羹"];

export const mockRecipes: Recipe[] = [
  {
    id: "recipe-farm-bowl",
    name: "农家一碗香",
    category: "荤菜",
    tags: ["下饭", "荤菜"],
    source: "howtocook",
    summary: "五花肉、鸡蛋和青椒一起炒，适合米饭党。",
    ingredients: [
      { name: "五花肉", amount: "150g" },
      { name: "鸡蛋", amount: "2 个" },
      { name: "青椒", amount: "2 根" },
    ],
    steps: ["五花肉煸出油脂", "鸡蛋煎成块", "青椒断生后合炒调味"],
    records: { wantToCook: false, plannedCount: 1, cookedCount: 2 },
  },
  {
    id: "recipe-tomato-egg",
    name: "番茄炒蛋",
    category: "家常菜",
    tags: ["素菜", "快手"],
    source: "custom",
    summary: "十分钟快手菜，酸甜下饭，适合不知道吃什么的时候。",
    ingredients: [
      { name: "番茄", amount: "2 个" },
      { name: "鸡蛋", amount: "3 个" },
      { name: "小葱", amount: "少许" },
    ],
    steps: ["番茄切块，鸡蛋打散", "先炒鸡蛋盛出", "番茄炒出汁后倒回鸡蛋"],
    records: { wantToCook: true, plannedCount: 0, cookedCount: 5 },
  },
  {
    id: "recipe-winter-melon-ribs",
    name: "冬瓜排骨汤",
    category: "汤羹",
    tags: ["汤羹", "暖胃"],
    source: "howtocook",
    summary: "清淡暖胃的汤，适合周末慢慢炖。",
    ingredients: [
      { name: "排骨", amount: "400g" },
      { name: "冬瓜", amount: "半块" },
      { name: "姜片", amount: "3 片" },
    ],
    steps: ["排骨焯水", "加姜片炖 30 分钟", "放冬瓜煮软后调盐"],
    records: { wantToCook: false, plannedCount: 1, cookedCount: 1 },
  },
  {
    id: "recipe-green-pepper-pork",
    name: "青椒肉丝",
    category: "荤菜",
    tags: ["荤菜", "下饭"],
    source: "howtocook",
    summary: "经典家常下饭菜，青椒爽脆、肉丝嫩滑。",
    ingredients: [
      { name: "里脊肉", amount: "200g" },
      { name: "青椒", amount: "3 根" },
      { name: "蒜", amount: "2 瓣" },
    ],
    steps: ["肉丝腌制 10 分钟", "青椒切丝", "大火快炒后调味"],
    records: { wantToCook: false, plannedCount: 0, cookedCount: 3 },
  },
  {
    id: "recipe-garlic-lettuce",
    name: "蒜蓉油麦菜",
    category: "素菜",
    tags: ["素菜", "快手", "清爽"],
    source: "custom",
    summary: "八分钟上桌的绿色蔬菜，清爽不腻。",
    ingredients: [
      { name: "油麦菜", amount: "1 把" },
      { name: "蒜", amount: "4 瓣" },
    ],
    steps: ["油麦菜洗净切段", "蒜末爆香", "大火快炒调味"],
    records: { wantToCook: true, plannedCount: 0, cookedCount: 2 },
  },
  {
    id: "recipe-seaweed-egg-soup",
    name: "紫菜蛋花汤",
    category: "汤羹",
    tags: ["汤羹", "快手", "清淡"],
    source: "custom",
    summary: "简单快手汤，适合配炒饭或拌面。",
    ingredients: [
      { name: "紫菜", amount: "一小把" },
      { name: "鸡蛋", amount: "1 个" },
      { name: "虾皮", amount: "少许" },
    ],
    steps: ["水开后下紫菜和虾皮", "淋入蛋液", "加盐和香油"],
    records: { wantToCook: false, plannedCount: 0, cookedCount: 4 },
  },
  {
    id: "recipe-scallion-noodles",
    name: "葱油拌面",
    category: "主食",
    tags: ["主食", "快手", "省心"],
    source: "howtocook",
    summary: "小葱熬油拌面，适合一个人的午饭。",
    ingredients: [
      { name: "面条", amount: "1 把" },
      { name: "小葱", amount: "1 把" },
      { name: "酱油", amount: "适量" },
    ],
    steps: ["小葱切段熬香", "调酱油和糖", "面条煮好后拌匀"],
    records: { wantToCook: false, plannedCount: 0, cookedCount: 3 },
  },
  {
    id: "recipe-cabbage",
    name: "手撕包菜",
    category: "素菜",
    tags: ["素菜", "家常"],
    source: "howtocook",
    summary: "爽脆简单，适合作为晚饭配菜。",
    ingredients: [
      { name: "包菜", amount: "半颗" },
      { name: "干辣椒", amount: "2 根" },
      { name: "蒜", amount: "2 瓣" },
    ],
    steps: ["包菜手撕成片", "蒜和干辣椒爆香", "大火快炒"],
    records: { wantToCook: false, plannedCount: 0, cookedCount: 1 },
  },
];
